# Generated by Django 3.2.25 on 2026-04-04 02:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('root', '0001_initial'),
        ('locations', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CandidateProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=150)),
                ('last_name', models.CharField(max_length=150)),
                ('date_of_birth', models.DateField()),
                ('place_of_birth', models.CharField(blank=True, max_length=255, null=True)),
                ('national_id_number', models.CharField(max_length=30, unique=True)),
                ('email', models.EmailField(max_length=254)),
                ('phone_number', models.CharField(max_length=30)),
                ('address', models.TextField(blank=True, null=True)),
                ('current_administration', models.CharField(max_length=255)),
                ('current_position_grade', models.CharField(max_length=255)),
                ('current_function', models.CharField(blank=True, max_length=255, null=True)),
                ('is_tenured_employee', models.BooleanField(default=False)),
                ('years_of_seniority', models.PositiveIntegerField(default=0)),
                ('years_of_effective_service', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('commune', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='candidate_profiles', to='locations.commune')),
                ('wilaya', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='candidate_profiles', to='locations.wilaya')),
            ],
            options={
                'ordering': ['last_name', 'first_name'],
            },
        ),
        migrations.CreateModel(
            name='Application',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('application_number', models.CharField(max_length=50, unique=True)),
                ('tracking_code', models.CharField(max_length=100, unique=True)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('submitted', 'Submitted'), ('under_review', 'Under Review'), ('preselected', 'Preselected'), ('rejected', 'Rejected'), ('interview_scheduled', 'Interview Scheduled'), ('interview_completed', 'Interview Completed'), ('final_accepted', 'Final Accepted'), ('final_rejected', 'Final Rejected')], default='draft', max_length=30)),
                ('is_eligible', models.BooleanField(default=True)),
                ('rejection_reason', models.TextField(blank=True, null=True)),
                ('admin_notes', models.TextField(blank=True, null=True)),
                ('submitted_at', models.DateTimeField(blank=True, null=True)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('candidate', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='applications', to='applications.candidateprofile')),
                ('poste', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='applications', to='root.poste')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
