# Generated by Django 6.0.4 on 2026-05-16 13:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('locations', '0001_initial'),
        ('root', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CandidateProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=150, verbose_name='الاسم')),
                ('last_name', models.CharField(max_length=150, verbose_name='اللقب')),
                ('date_of_birth', models.DateField(verbose_name='تاريخ الميلاد')),
                ('place_of_birth', models.CharField(blank=True, max_length=255, null=True, verbose_name='مكان الميلاد')),
                ('gender', models.CharField(blank=True, choices=[('male', 'ذكر'), ('female', 'أنثى')], max_length=10, null=True, verbose_name='الجنس')),
                ('national_id_number', models.CharField(max_length=30, verbose_name='رقم التعريف الوطني')),
                ('email', models.EmailField(max_length=254, verbose_name='البريد الإلكتروني')),
                ('phone_number', models.CharField(max_length=30, verbose_name='رقم الهاتف')),
                ('address', models.TextField(blank=True, null=True, verbose_name='العنوان')),
                ('current_administration', models.CharField(max_length=255, verbose_name='الإدارة الحالية')),
                ('current_position_grade', models.CharField(max_length=255, verbose_name='الرتبة الحالية')),
                ('current_function', models.CharField(blank=True, max_length=255, null=True, verbose_name='الوظيفة الحالية')),
                ('tenure_decision_date', models.DateField(verbose_name='تاريخ قرار الترسيم')),
                ('years_of_seniority', models.PositiveIntegerField(default=0, verbose_name='سنوات الأقدمية')),
                ('years_of_effective_service', models.PositiveIntegerField(default=0, verbose_name='سنوات الخدمة الفعلية')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('commune', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='candidate_profiles', to='locations.commune', verbose_name='البلدية')),
                ('wilaya', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='candidate_profiles', to='locations.wilaya', verbose_name='الولاية')),
            ],
            options={
                'verbose_name': 'ملف مترشح',
                'verbose_name_plural': 'ملفات المترشحين',
                'ordering': ['last_name', 'first_name'],
            },
        ),
        migrations.CreateModel(
            name='Application',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('application_number', models.CharField(blank=True, max_length=50, unique=True, verbose_name='رقم الطلب')),
                ('tracking_code', models.CharField(blank=True, max_length=100, unique=True, verbose_name='رمز التتبع')),
                ('status', models.CharField(choices=[('draft', 'مسودة'), ('submitted', 'مرسل'), ('under_review', 'قيد الدراسة'), ('incomplete', 'ملف ناقص'), ('preselected', 'مقبول أوليًا'), ('preliminary_rejected', 'مرفوض أوليًا'), ('interview_scheduled', 'تمت برمجة المقابلة'), ('interview_completed', 'أُجريت المقابلة'), ('no_show', 'لم يحضر المقابلة'), ('final_accepted', 'مقبول نهائيًا'), ('final_rejected', 'مرفوض نهائيًا'), ('waiting_list', 'قائمة الاحتياط')], db_index=True, default='draft', max_length=30, verbose_name='الحالة')),
                ('is_eligible', models.BooleanField(default=True, verbose_name='مؤهل مبدئيًا')),
                ('rejection_reason', models.TextField(blank=True, null=True, verbose_name='سبب الرفض')),
                ('admin_notes', models.TextField(blank=True, null=True, verbose_name='ملاحظات الإدارة')),
                ('motivation_text', models.TextField(blank=True, verbose_name='Motivation Letter')),
                ('submitted_at', models.DateTimeField(blank=True, null=True)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('preselected_at', models.DateTimeField(blank=True, null=True)),
                ('interview_scheduled_at', models.DateTimeField(blank=True, null=True)),
                ('interview_completed_at', models.DateTimeField(blank=True, null=True)),
                ('final_decision_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('poste', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='applications', to='root.poste', verbose_name='المنصب')),
                ('candidate', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='applications', to='applications.candidateprofile', verbose_name='المترشح')),
            ],
            options={
                'verbose_name': 'طلب ترشح',
                'verbose_name_plural': 'طلبات الترشح',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ApplicationChoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('priority', models.PositiveSmallIntegerField(verbose_name='الأولوية')),
                ('application', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='choices', to='applications.application', verbose_name='الطلب')),
                ('poste', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='root.poste', verbose_name='المنصب')),
            ],
            options={
                'verbose_name': 'اختيار منصب',
                'verbose_name_plural': 'اختيارات المناصب',
                'ordering': ['priority'],
                'constraints': [models.UniqueConstraint(fields=('application', 'poste'), name='unique_poste_per_application')],
                'unique_together': {('application', 'priority')},
            },
        ),
    ]
