# Generated by Django 3.2.25 on 2026-04-04 19:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('root', '0001_initial'),
        ('locations', '0001_initial'),
        ('applications', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='application',
            options={'ordering': ['-created_at'], 'verbose_name': 'طلب ترشح', 'verbose_name_plural': 'طلبات الترشح'},
        ),
        migrations.AlterModelOptions(
            name='candidateprofile',
            options={'ordering': ['last_name', 'first_name'], 'verbose_name': 'ملف مترشح', 'verbose_name_plural': 'ملفات المترشحين'},
        ),
        migrations.AddField(
            model_name='application',
            name='final_decision_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='application',
            name='interview_completed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='application',
            name='interview_scheduled_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='application',
            name='preselected_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='candidateprofile',
            name='gender',
            field=models.CharField(blank=True, choices=[('male', 'ذكر'), ('female', 'أنثى')], max_length=10, null=True, verbose_name='الجنس'),
        ),
        migrations.AlterField(
            model_name='application',
            name='admin_notes',
            field=models.TextField(blank=True, null=True, verbose_name='ملاحظات الإدارة'),
        ),
        migrations.AlterField(
            model_name='application',
            name='application_number',
            field=models.CharField(blank=True, max_length=50, unique=True, verbose_name='رقم الطلب'),
        ),
        migrations.AlterField(
            model_name='application',
            name='candidate',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='applications', to='applications.candidateprofile', verbose_name='المترشح'),
        ),
        migrations.AlterField(
            model_name='application',
            name='is_eligible',
            field=models.BooleanField(default=True, verbose_name='مؤهل مبدئيًا'),
        ),
        migrations.AlterField(
            model_name='application',
            name='poste',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='applications', to='root.poste', verbose_name='المنصب'),
        ),
        migrations.AlterField(
            model_name='application',
            name='rejection_reason',
            field=models.TextField(blank=True, null=True, verbose_name='سبب الرفض'),
        ),
        migrations.AlterField(
            model_name='application',
            name='status',
            field=models.CharField(choices=[('draft', 'مسودة'), ('submitted', 'مرسل'), ('under_review', 'قيد الدراسة'), ('incomplete', 'ملف ناقص'), ('preselected', 'مقبول أوليًا'), ('preliminary_rejected', 'مرفوض أوليًا'), ('interview_scheduled', 'تمت برمجة المقابلة'), ('interview_completed', 'أُجريت المقابلة'), ('no_show', 'لم يحضر المقابلة'), ('final_accepted', 'مقبول نهائيًا'), ('final_rejected', 'مرفوض نهائيًا'), ('waiting_list', 'قائمة الاحتياط')], db_index=True, default='draft', max_length=30, verbose_name='الحالة'),
        ),
        migrations.AlterField(
            model_name='application',
            name='tracking_code',
            field=models.CharField(blank=True, max_length=100, unique=True, verbose_name='رمز التتبع'),
        ),
        migrations.AlterField(
            model_name='candidateprofile',
            name='address',
            field=models.TextField(blank=True, null=True, verbose_name='العنوان'),
        ),
        migrations.AlterField(
            model_name='candidateprofile',
            name='commune',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='candidate_profiles', to='locations.commune', verbose_name='البلدية'),
        ),
        migrations.AlterField(
            model_name='candidateprofile',
            name='current_administration',
            field=models.CharField(max_length=255, verbose_name='الإدارة الحالية'),
        ),
        migrations.AlterField(
            model_name='candidateprofile',
            name='current_function',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='الوظيفة الحالية'),
        ),
        migrations.AlterField(
            model_name='candidateprofile',
            name='current_position_grade',
            field=models.CharField(max_length=255, verbose_name='الرتبة الحالية'),
        ),
        migrations.AlterField(
            model_name='candidateprofile',
            name='date_of_birth',
            field=models.DateField(verbose_name='تاريخ الميلاد'),
        ),
        migrations.AlterField(
            model_name='candidateprofile',
            name='email',
            field=models.EmailField(max_length=254, verbose_name='البريد الإلكتروني'),
        ),
        migrations.AlterField(
            model_name='candidateprofile',
            name='first_name',
            field=models.CharField(max_length=150, verbose_name='الاسم'),
        ),
        migrations.AlterField(
            model_name='candidateprofile',
            name='is_tenured_employee',
            field=models.BooleanField(default=False, verbose_name='موظف مرسم'),
        ),
        migrations.AlterField(
            model_name='candidateprofile',
            name='last_name',
            field=models.CharField(max_length=150, verbose_name='اللقب'),
        ),
        migrations.AlterField(
            model_name='candidateprofile',
            name='national_id_number',
            field=models.CharField(max_length=30, unique=True, verbose_name='رقم التعريف الوطني'),
        ),
        migrations.AlterField(
            model_name='candidateprofile',
            name='phone_number',
            field=models.CharField(max_length=30, verbose_name='رقم الهاتف'),
        ),
        migrations.AlterField(
            model_name='candidateprofile',
            name='place_of_birth',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='مكان الميلاد'),
        ),
        migrations.AlterField(
            model_name='candidateprofile',
            name='wilaya',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='candidate_profiles', to='locations.wilaya', verbose_name='الولاية'),
        ),
        migrations.AlterField(
            model_name='candidateprofile',
            name='years_of_effective_service',
            field=models.PositiveIntegerField(default=0, verbose_name='سنوات الخدمة الفعلية'),
        ),
        migrations.AlterField(
            model_name='candidateprofile',
            name='years_of_seniority',
            field=models.PositiveIntegerField(default=0, verbose_name='سنوات الأقدمية'),
        ),
        migrations.AddConstraint(
            model_name='application',
            constraint=models.UniqueConstraint(fields=('candidate', 'poste'), name='unique_candidate_application_per_poste'),
        ),
    ]
