# Generated by Django 6.0.4 on 2026-05-16 13:57

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CompletionRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.TextField(verbose_name='الوثائق أو المعلومات المطلوبة')),
                ('deadline', models.DateTimeField(verbose_name='آخر أجل للاستكمال')),
                ('is_resolved', models.BooleanField(default=False, verbose_name='تم الاستكمال')),
                ('resolved_at', models.DateTimeField(blank=True, null=True, verbose_name='تاريخ الاستكمال')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('application', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='completion_requests', to='applications.application', verbose_name='الطلب')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='تم الإنشاء بواسطة')),
            ],
            options={
                'verbose_name': 'طلب استكمال',
                'verbose_name_plural': 'طلبات الاستكمال',
                'ordering': ['-created_at'],
            },
        ),
    ]
