# Generated by Django 3.2.25 on 2026-04-08 23:53

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0002_auto_20260404_2016'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='candidateprofile',
            name='is_tenured_employee',
        ),
        migrations.AddField(
            model_name='candidateprofile',
            name='tenure_decision_date',
            field=models.DateField(default=django.utils.timezone.now, verbose_name='تاريخ قرار الترسيم'),
        ),
    ]
