# Generated by Django 3.2.25 on 2026-04-08 23:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0003_auto_20260409_0053'),
    ]

    operations = [
        migrations.AlterField(
            model_name='candidateprofile',
            name='tenure_decision_date',
            field=models.DateField(verbose_name='تاريخ قرار الترسيم'),
        ),
    ]
