# Generated by Django 6.0.4 on 2026-05-16 16:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0004_application_evaluation_comment_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='application',
            options={'ordering': ['-created_at'], 'permissions': [('can_review_applications', 'Can review applications'), ('can_score_applications', 'Can score applications'), ('can_manage_interviews', 'Can manage interviews'), ('can_finalize_applications', 'Can finalize applications')], 'verbose_name': 'طلب ترشح', 'verbose_name_plural': 'طلبات الترشح'},
        ),
    ]
