# Generated by Django 6.0.4 on 2026-04-18 13:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0004_alter_candidateprofile_tenure_decision_date'),
        ('root', '0009_poste_sub_direction'),
    ]

    operations = [
        migrations.CreateModel(
            name='ApplicationChoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('priority', models.PositiveSmallIntegerField(verbose_name='الأولوية')),
                ('application', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='choices', to='applications.application', verbose_name='الطلب')),
                ('poste', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='root.poste', verbose_name='المنصب')),
            ],
            options={
                'verbose_name': 'اختيار منصب',
                'verbose_name_plural': 'اختيارات المناصب',
                'ordering': ['priority'],
                'unique_together': {('application', 'priority')},
            },
        ),
    ]
