# Generated by Django 6.0.4 on 2026-04-18 15:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0005_applicationchoice'),
        ('root', '0009_poste_sub_direction'),
    ]

    operations = [
        migrations.AddField(
            model_name='application',
            name='motivation_text',
            field=models.TextField(blank=True, verbose_name='Motivation Letter'),
        ),
        migrations.AddConstraint(
            model_name='applicationchoice',
            constraint=models.UniqueConstraint(fields=('application', 'poste'), name='unique_poste_per_application'),
        ),
    ]
