# Generated by Django 6.0.4 on 2026-05-16 13:51

import django.db.models.deletion
import documents.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('applications', '0001_initial'),
        ('root', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DocumentType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('is_required', models.BooleanField(default=True)),
                ('is_active', models.BooleanField(default=True)),
                ('display_order', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['display_order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='ApplicationDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to=documents.models.application_document_upload_to)),
                ('original_filename', models.CharField(blank=True, max_length=255, null=True)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('application', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='applications.application')),
                ('document_type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='application_documents', to='documents.documenttype')),
            ],
            options={
                'ordering': ['document_type__display_order', '-uploaded_at'],
                'unique_together': {('application', 'document_type')},
            },
        ),
        migrations.CreateModel(
            name='PosteDocumentRequirement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_required', models.BooleanField(default=True, verbose_name='وثيقة مطلوبة')),
                ('allowed_extensions', models.CharField(blank=True, help_text='مثال: jpg,jpeg,png', max_length=255, verbose_name='الامتدادات المسموحة')),
                ('max_file_size_mb', models.PositiveIntegerField(default=5, verbose_name='الحد الأقصى للحجم (MB)')),
                ('help_text', models.CharField(blank=True, max_length=255, null=True, verbose_name='نص مساعد')),
                ('display_order', models.PositiveIntegerField(default=0, verbose_name='ترتيب العرض')),
                ('is_active', models.BooleanField(default=True, verbose_name='مفعل')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('document_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='poste_requirements', to='documents.documenttype', verbose_name='نوع الوثيقة')),
                ('poste', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='document_requirements', to='root.poste', verbose_name='المنصب')),
            ],
            options={
                'verbose_name': 'متطلب وثيقة لمنصب',
                'verbose_name_plural': 'متطلبات الوثائق للمناصب',
                'ordering': ['display_order', 'id'],
                'constraints': [models.UniqueConstraint(fields=('poste', 'document_type'), name='unique_poste_document_requirement')],
            },
        ),
    ]
