# Generated by Django 3.2.25 on 2026-04-10 15:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('root', '0004_auto_20260405_2239'),
        ('documents', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PosteDocumentRequirement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_required', models.BooleanField(default=True, verbose_name='وثيقة مطلوبة')),
                ('allowed_extensions', models.CharField(blank=True, help_text='مثال: jpg,jpeg,png', max_length=255, verbose_name='الامتدادات المسموحة')),
                ('max_file_size_mb', models.PositiveIntegerField(default=5, verbose_name='الحد الأقصى للحجم (MB)')),
                ('help_text', models.CharField(blank=True, max_length=255, null=True, verbose_name='نص مساعد')),
                ('display_order', models.PositiveIntegerField(default=0, verbose_name='ترتيب العرض')),
                ('is_active', models.BooleanField(default=True, verbose_name='مفعل')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('document_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='poste_requirements', to='documents.documenttype', verbose_name='نوع الوثيقة')),
                ('poste', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='document_requirements', to='root.poste', verbose_name='المنصب')),
            ],
            options={
                'verbose_name': 'متطلب وثيقة لمنصب',
                'verbose_name_plural': 'متطلبات الوثائق للمناصب',
                'ordering': ['display_order', 'id'],
            },
        ),
        migrations.AddConstraint(
            model_name='postedocumentrequirement',
            constraint=models.UniqueConstraint(fields=('poste', 'document_type'), name='unique_poste_document_requirement'),
        ),
    ]
