# Generated by Django 3.2.25 on 2026-04-10 20:15

from django.db import migrations, models
import documents.models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0002_auto_20260410_1633'),
    ]

    operations = [
        migrations.AlterField(
            model_name='applicationdocument',
            name='file',
            field=models.FileField(upload_to=documents.models.application_document_upload_to),
        ),
    ]
