# Generated by Django 6.0.4 on 2026-05-16 13:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='LegalReference',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='العنوان')),
                ('reference_number', models.CharField(blank=True, max_length=100, null=True, verbose_name='رقم المرجع')),
                ('published_date', models.DateField(blank=True, null=True, verbose_name='تاريخ النشر')),
                ('description', models.TextField(blank=True, null=True, verbose_name='الوصف')),
                ('document_url', models.URLField(blank=True, null=True, verbose_name='رابط الوثيقة')),
                ('reference_type', models.CharField(choices=[('general', 'نصوص عامة'), ('recruitment', 'الترشح والتوظيف'), ('senior_positions', 'الوظائف والمناصب العليا'), ('documents', 'الوثائق والملفات'), ('data_protection', 'حماية المعطيات'), ('interviews', 'المقابلات والإجراءات')], default='general', max_length=50, verbose_name='نوع المرجع')),
                ('is_active', models.BooleanField(default=True, verbose_name='نشط')),
                ('display_order', models.PositiveIntegerField(default=0, verbose_name='ترتيب الظهور')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإنشاء')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاريخ التحديث')),
            ],
            options={
                'verbose_name': 'مرجع قانوني',
                'verbose_name_plural': 'المراجع القانونية',
                'ordering': ['display_order', '-published_date', 'title'],
            },
        ),
        migrations.CreateModel(
            name='Poste',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='عنوان المنصب')),
                ('slug', models.SlugField(blank=True, max_length=255, unique=True, verbose_name='المعرّف النصي')),
                ('direction', models.CharField(max_length=255, verbose_name='المديرية / الهيكل')),
                ('sub_direction', models.CharField(blank=True, max_length=255, null=True, verbose_name='المديرية الفرعية / الهيكل')),
                ('positions_count', models.PositiveIntegerField(default=1, verbose_name='عدد المناصب')),
                ('description', models.TextField(blank=True, null=True, verbose_name='الوصف')),
                ('poste_type', models.CharField(choices=[('transfer', 'وظائف عليا'), ('detachment', 'مناصب عليا'), ('head_office', 'رتب')], default='head_office', max_length=20, verbose_name='نوع المنصب')),
                ('is_open', models.BooleanField(default=True, verbose_name='مفتوح للترشح')),
                ('publish_date', models.DateField(verbose_name='تاريخ النشر')),
                ('deadline', models.DateField(blank=True, null=True, verbose_name='آخر أجل للترشح')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإنشاء')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاريخ التحديث')),
                ('legal_reference', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='postes', to='root.legalreference', verbose_name='المرجع القانوني')),
            ],
            options={
                'verbose_name': 'منصب / وظيفة',
                'verbose_name_plural': 'المناصب والوظائف',
                'ordering': ['-publish_date', '-created_at'],
            },
        ),
    ]
