# Generated by Django 3.2.25 on 2026-04-05 19:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('root', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='LegalReference',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='عنوان المرجع')),
                ('description', models.TextField(blank=True, null=True, verbose_name='وصف')),
                ('reference_number', models.CharField(blank=True, max_length=100, null=True, verbose_name='رقم المرجع')),
                ('published_date', models.DateField(blank=True, null=True, verbose_name='تاريخ النشر')),
                ('document_url', models.URLField(blank=True, null=True, verbose_name='رابط الوثيقة')),
            ],
        ),
        migrations.AddField(
            model_name='poste',
            name='poste_type',
            field=models.CharField(choices=[('transfer', 'وظيفة عن طريق النقل'), ('detachment', 'منصب عالي عن طريق الانتداب'), ('head_office', 'رئيس مكتب')], default='head_office', max_length=20, verbose_name='نوع المنصب'),
        ),
        migrations.AddField(
            model_name='poste',
            name='legal_reference',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='root.legalreference', verbose_name='المرجع القانوني'),
        ),
    ]
