# Generated by Django 3.2.25 on 2026-04-05 20:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('root', '0002_auto_20260405_2047'),
    ]

    operations = [
        migrations.AddField(
            model_name='poste',
            name='slug',
            field=models.SlugField(blank=True, max_length=255, unique=True),
        ),
    ]
