# Generated by Django 3.2.25 on 2026-04-05 21:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('root', '0003_poste_slug'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='legalreference',
            options={'ordering': ['-published_date', 'title'], 'verbose_name': 'مرجع قانوني', 'verbose_name_plural': 'المراجع القانونية'},
        ),
        migrations.AlterModelOptions(
            name='poste',
            options={'ordering': ['-publish_date', '-created_at'], 'verbose_name': 'منصب / وظيفة', 'verbose_name_plural': 'المناصب والوظائف'},
        ),
        migrations.AlterField(
            model_name='poste',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإنشاء'),
        ),
        migrations.AlterField(
            model_name='poste',
            name='deadline',
            field=models.DateField(blank=True, null=True, verbose_name='آخر أجل للترشح'),
        ),
        migrations.AlterField(
            model_name='poste',
            name='description',
            field=models.TextField(blank=True, null=True, verbose_name='الوصف'),
        ),
        migrations.AlterField(
            model_name='poste',
            name='direction',
            field=models.CharField(max_length=255, verbose_name='المديرية / الهيكل'),
        ),
        migrations.AlterField(
            model_name='poste',
            name='is_open',
            field=models.BooleanField(default=True, verbose_name='مفتوح للترشح'),
        ),
        migrations.AlterField(
            model_name='poste',
            name='legal_reference',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='postes', to='root.legalreference', verbose_name='المرجع القانوني'),
        ),
        migrations.AlterField(
            model_name='poste',
            name='positions_count',
            field=models.PositiveIntegerField(default=1, verbose_name='عدد المناصب'),
        ),
        migrations.AlterField(
            model_name='poste',
            name='publish_date',
            field=models.DateField(verbose_name='تاريخ النشر'),
        ),
        migrations.AlterField(
            model_name='poste',
            name='slug',
            field=models.SlugField(blank=True, max_length=255, unique=True, verbose_name='المعرّف النصي'),
        ),
        migrations.AlterField(
            model_name='poste',
            name='title',
            field=models.CharField(max_length=255, verbose_name='عنوان المنصب'),
        ),
        migrations.AlterField(
            model_name='poste',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='تاريخ التحديث'),
        ),
    ]
