# Generated by Django 3.2.25 on 2026-04-10 23:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('root', '0004_auto_20260405_2239'),
    ]

    operations = [
        migrations.AlterField(
            model_name='poste',
            name='poste_type',
            field=models.CharField(choices=[('transfer', 'وظائف عليا'), ('detachment', 'مناصب عليا'), ('head_office', 'رتب')], default='head_office', max_length=20, verbose_name='نوع المنصب'),
        ),
    ]
