# Generated by Django 3.2.25 on 2026-04-11 00:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('root', '0005_alter_poste_poste_type'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='legalreference',
            options={'ordering': ['display_order', '-published_date', 'title'], 'verbose_name': 'مرجع قانوني', 'verbose_name_plural': 'المراجع القانونية'},
        ),
        migrations.AddField(
            model_name='legalreference',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True, verbose_name='تاريخ الإنشاء'),
        ),
        migrations.AddField(
            model_name='legalreference',
            name='display_order',
            field=models.PositiveIntegerField(default=0, verbose_name='ترتيب الظهور'),
        ),
        migrations.AddField(
            model_name='legalreference',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='نشط'),
        ),
        migrations.AddField(
            model_name='legalreference',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, null=True, verbose_name='تاريخ التحديث'),
        ),
        migrations.AlterField(
            model_name='legalreference',
            name='description',
            field=models.TextField(blank=True, null=True, verbose_name='الوصف'),
        ),
        migrations.AlterField(
            model_name='legalreference',
            name='title',
            field=models.CharField(max_length=255, verbose_name='العنوان'),
        ),
    ]
