# Generated by Django 3.2.25 on 2026-04-11 00:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('root', '0007_auto_20260411_0144'),
    ]

    operations = [
        migrations.AddField(
            model_name='legalreference',
            name='reference_type',
            field=models.CharField(choices=[('general', 'نصوص عامة'), ('recruitment', 'الترشح والتوظيف'), ('senior_positions', 'الوظائف والمناصب العليا'), ('documents', 'الوثائق والملفات'), ('data_protection', 'حماية المعطيات'), ('interviews', 'المقابلات والإجراءات')], default='general', max_length=50, verbose_name='نوع المرجع'),
        ),
    ]
