# Generated by Django 3.2.25 on 2026-04-11 13:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('root', '0008_legalreference_reference_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='poste',
            name='sub_direction',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='المديرية الفرعية / الهيكل'),
        ),
    ]
