# Generated by Django 6.0.4 on 2026-05-16 13:51

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('applications', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='InterviewSchedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('interview_date', models.DateField(verbose_name='تاريخ المقابلة')),
                ('interview_time', models.TimeField(verbose_name='وقت المقابلة')),
                ('location', models.CharField(max_length=255, verbose_name='مكان المقابلة')),
                ('note', models.TextField(blank=True, null=True, verbose_name='ملاحظة')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإنشاء')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاريخ التحديث')),
                ('application', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='interview_schedule', to='applications.application', verbose_name='الطلب')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_interviews', to=settings.AUTH_USER_MODEL, verbose_name='أُنشئت بواسطة')),
            ],
            options={
                'verbose_name': 'برمجة مقابلة',
                'verbose_name_plural': 'برمجة المقابلات',
                'ordering': ['-interview_date', '-interview_time'],
            },
        ),
        migrations.CreateModel(
            name='ApplicationTracking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('draft', 'مسودة'), ('submitted', 'مرسل'), ('under_review', 'قيد الدراسة'), ('incomplete', 'ملف ناقص'), ('preselected', 'مقبول أوليًا'), ('preliminary_rejected', 'مرفوض أوليًا'), ('interview_scheduled', 'تمت برمجة المقابلة'), ('interview_completed', 'أُجريت المقابلة'), ('no_show', 'لم يحضر المقابلة'), ('final_accepted', 'مقبول نهائيًا'), ('final_rejected', 'مرفوض نهائيًا'), ('waiting_list', 'قائمة الاحتياط')], max_length=30, verbose_name='الحالة')),
                ('note', models.TextField(blank=True, null=True, verbose_name='ملاحظة')),
                ('is_visible_to_candidate', models.BooleanField(default=True, verbose_name='ظاهر للمترشح')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإنشاء')),
                ('application', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tracking_entries', to='applications.application', verbose_name='الطلب')),
                ('changed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='application_tracking_entries', to=settings.AUTH_USER_MODEL, verbose_name='تم التغيير بواسطة')),
            ],
            options={
                'verbose_name': 'سجل تتبع',
                'verbose_name_plural': 'سجلات التتبع',
                'ordering': ['created_at'],
                'indexes': [models.Index(fields=['application', 'created_at'], name='tracking_ap_applica_f1030e_idx'), models.Index(fields=['status'], name='tracking_ap_status_6c9592_idx')],
            },
        ),
    ]
