# Generated by Django 3.2.25 on 2026-04-04 19:18

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0002_auto_20260404_2016'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('tracking', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='applicationtracking',
            options={'ordering': ['created_at'], 'verbose_name': 'سجل تتبع', 'verbose_name_plural': 'سجلات التتبع'},
        ),
        migrations.AlterModelOptions(
            name='interviewschedule',
            options={'ordering': ['-interview_date', '-interview_time'], 'verbose_name': 'برمجة مقابلة', 'verbose_name_plural': 'برمجة المقابلات'},
        ),
        migrations.AlterField(
            model_name='applicationtracking',
            name='application',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tracking_entries', to='applications.application', verbose_name='الطلب'),
        ),
        migrations.AlterField(
            model_name='applicationtracking',
            name='changed_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='application_tracking_entries', to=settings.AUTH_USER_MODEL, verbose_name='تم التغيير بواسطة'),
        ),
        migrations.AlterField(
            model_name='applicationtracking',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإنشاء'),
        ),
        migrations.AlterField(
            model_name='applicationtracking',
            name='is_visible_to_candidate',
            field=models.BooleanField(default=True, verbose_name='ظاهر للمترشح'),
        ),
        migrations.AlterField(
            model_name='applicationtracking',
            name='note',
            field=models.TextField(blank=True, null=True, verbose_name='ملاحظة'),
        ),
        migrations.AlterField(
            model_name='applicationtracking',
            name='status',
            field=models.CharField(choices=[('draft', 'مسودة'), ('submitted', 'مرسل'), ('under_review', 'قيد الدراسة'), ('incomplete', 'ملف ناقص'), ('preselected', 'مقبول أوليًا'), ('preliminary_rejected', 'مرفوض أوليًا'), ('interview_scheduled', 'تمت برمجة المقابلة'), ('interview_completed', 'أُجريت المقابلة'), ('no_show', 'لم يحضر المقابلة'), ('final_accepted', 'مقبول نهائيًا'), ('final_rejected', 'مرفوض نهائيًا'), ('waiting_list', 'قائمة الاحتياط')], max_length=30, verbose_name='الحالة'),
        ),
        migrations.AlterField(
            model_name='interviewschedule',
            name='application',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='interview_schedule', to='applications.application', verbose_name='الطلب'),
        ),
        migrations.AlterField(
            model_name='interviewschedule',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإنشاء'),
        ),
        migrations.AlterField(
            model_name='interviewschedule',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_interviews', to=settings.AUTH_USER_MODEL, verbose_name='أُنشئت بواسطة'),
        ),
        migrations.AlterField(
            model_name='interviewschedule',
            name='interview_date',
            field=models.DateField(verbose_name='تاريخ المقابلة'),
        ),
        migrations.AlterField(
            model_name='interviewschedule',
            name='interview_time',
            field=models.TimeField(verbose_name='وقت المقابلة'),
        ),
        migrations.AlterField(
            model_name='interviewschedule',
            name='location',
            field=models.CharField(max_length=255, verbose_name='مكان المقابلة'),
        ),
        migrations.AlterField(
            model_name='interviewschedule',
            name='note',
            field=models.TextField(blank=True, null=True, verbose_name='ملاحظة'),
        ),
        migrations.AlterField(
            model_name='interviewschedule',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='تاريخ التحديث'),
        ),
        migrations.AddIndex(
            model_name='applicationtracking',
            index=models.Index(fields=['application', 'created_at'], name='tracking_ap_applica_f1030e_idx'),
        ),
        migrations.AddIndex(
            model_name='applicationtracking',
            index=models.Index(fields=['status'], name='tracking_ap_status_6c9592_idx'),
        ),
    ]
