# Generated by Django 6.0.4 on 2026-05-16 16:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracking', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='interviewschedule',
            name='summons_file',
            field=models.FileField(blank=True, null=True, upload_to='interview_summons/', verbose_name='ملف الاستدعاء'),
        ),
    ]
