# Generated by Django 6.0.4 on 2026-05-16 13:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Wilaya',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=2, unique=True)),
                ('name_fr', models.CharField(max_length=100)),
                ('name_ar', models.CharField(max_length=100)),
            ],
            options={
                'ordering': ['code'],
            },
        ),
        migrations.CreateModel(
            name='Commune',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=10)),
                ('name_fr', models.CharField(max_length=120)),
                ('name_ar', models.CharField(blank=True, max_length=120, null=True)),
                ('wilaya', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='communes', to='locations.wilaya')),
            ],
            options={
                'ordering': ['wilaya__code', 'name_ar'],
                'unique_together': {('wilaya', 'name_ar')},
            },
        ),
    ]
