# Generated by Django 6.0.4 on 2026-05-16 13:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('applications', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='NotificationLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('to_email', models.EmailField(max_length=254, verbose_name='البريد المرسل إليه')),
                ('subject', models.CharField(max_length=200, verbose_name='الموضوع')),
                ('template_name', models.CharField(blank=True, max_length=100, null=True, verbose_name='القالب')),
                ('status', models.CharField(choices=[('SENT', 'تم الإرسال'), ('FAILED', 'فشل الإرسال')], max_length=20, verbose_name='الحالة')),
                ('error', models.TextField(blank=True, null=True, verbose_name='تفاصيل الخطأ')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإنشاء')),
                ('application', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='notification_logs', to='applications.application', verbose_name='الطلب المرتبط')),
            ],
            options={
                'verbose_name': 'سجل إشعار',
                'verbose_name_plural': 'سجلات الإشعارات',
                'ordering': ['-created_at'],
            },
        ),
    ]
