# Generated by Django 6.0.4 on 2026-04-11 23:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0004_alter_candidateprofile_tenure_decision_date'),
        ('notifications', '0002_notificationlog_application'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='notificationlog',
            options={'ordering': ['-created_at'], 'verbose_name': 'سجل إشعار', 'verbose_name_plural': 'سجلات الإشعارات'},
        ),
        migrations.AlterField(
            model_name='notificationlog',
            name='application',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='notification_logs', to='applications.application', verbose_name='الطلب المرتبط'),
        ),
        migrations.AlterField(
            model_name='notificationlog',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإنشاء'),
        ),
        migrations.AlterField(
            model_name='notificationlog',
            name='error',
            field=models.TextField(blank=True, null=True, verbose_name='تفاصيل الخطأ'),
        ),
        migrations.AlterField(
            model_name='notificationlog',
            name='status',
            field=models.CharField(choices=[('SENT', 'تم الإرسال'), ('FAILED', 'فشل الإرسال')], max_length=20, verbose_name='الحالة'),
        ),
        migrations.AlterField(
            model_name='notificationlog',
            name='subject',
            field=models.CharField(max_length=200, verbose_name='الموضوع'),
        ),
        migrations.AlterField(
            model_name='notificationlog',
            name='template_name',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='القالب'),
        ),
        migrations.AlterField(
            model_name='notificationlog',
            name='to_email',
            field=models.EmailField(max_length=254, verbose_name='البريد المرسل إليه'),
        ),
    ]
